### ISSUE TITLE
Error "int too big to convert" when I use the offline model downloaded from hugging face

### ISSUE THREAD

**Issue by Persvadisto** [Tiiiger/bert_score#135]
I've downloaded roberta-large (from hugging face‘s website) to "./model_offline/roberta-large". And then I tried to do 
```
bert-score -r example/refs.txt -c example/hyps.txt --lang en -l 17 -m ./model_offline/roberta-large
```
It didn't work and it seemed to be the problem with the tokenization. The error message tells int too big to convert
```
Some weights of the model checkpoint at ./model_offline/roberta-large were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.bias',
'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertF
orSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClas
sification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "C:\Users\86189\bert_score\Scripts\bert-score-script.py", line 33, in <module>
    sys.exit(load_entry_point('bert-score==0.3.11', 'console_scripts', 'bert-score')())
  File "c:\users\86189\bert_score\lib\site-packages\bert_score_cli\score.py", line 59, in main
    all_preds, hash_code = bert_score.score(
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\score.py", line 131, in score
    all_preds = bert_cos_score_idf(
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\utils.py", line 528, in bert_cos_score_idf
    embs, masks, padded_idf = get_bert_embedding(
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\utils.py", line 399, in get_bert_embedding
    padded_sens, padded_idf, lens, mask = collate_idf(all_sens, tokenizer, idf_dict, device=device)
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\utils.py", line 371, in collate_idf
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\utils.py", line 371, in <listcomp>
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "c:\users\86189\bert_score\lib\site-packages\bert_score\utils.py", line 213, in sent_encode
    return tokenizer.encode(
  File "c:\users\86189\bert_score\lib\site-packages\transformers\tokenization_utils_base.py", line 2278, in encode
    encoded_inputs = self.encode_plus(
  File "c:\users\86189\bert_score\lib\site-packages\transformers\tokenization_utils_base.py", line 2610, in encode_plus
    return self._encode_plus(
  File "c:\users\86189\bert_score\lib\site-packages\transformers\models\roberta\tokenization_roberta_fast.py", line 273, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "c:\users\86189\bert_score\lib\site-packages\transformers\tokenization_utils_fast.py", line 499, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "c:\users\86189\bert_score\lib\site-packages\transformers\models\roberta\tokenization_roberta_fast.py", line 263, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "c:\users\86189\bert_score\lib\site-packages\transformers\tokenization_utils_fast.py", line 418, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "c:\users\86189\bert_score\lib\site-packages\transformers\tokenization_utils_fast.py", line 374, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: int too big to convert
```
And I tried to switch to another offline model bert-base-uncased and the output was still the same. However, when I use the online model the error is gone. I am trying to fine the reason cuz I want to use another bert trained by myself afterwards. How should I solve this bug?
Thanks for your attention!

**Comment by Tiiiger** [comment]
Hi what version of transformers are you on

**Comment by Persvadisto** [comment]
it's 4.21.2

**Comment by Persvadisto** [comment]
And i found if adding --use_fast_tokenizer the bug also disappeared..

**Comment by Tiiiger** [comment]
Glad you found the error. I think this is more an issue from the HF transformers library. Closing this for now.

**Comment by Canonize** [comment]
> And i found if adding --use_fast_tokenizer the bug also disappeared..

The same error occured to me when I use offline model bert-base-uncased. 
`File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/scorer.py", line 229, in score
    all_layers=self.all_layers,
  File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/utils.py", line 617, in bert_cos_score_idf
    sen_batch, model, tokenizer, idf_dict, device=device, all_layers=all_layers
  File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/utils.py", line 446, in get_bert_embedding
    all_sens, tokenizer, idf_dict, device=device
  File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/utils.py", line 409, in collate_idf
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/utils.py", line 409, in <listcomp>
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "/home/cqt/.local/lib/python3.6/site-packages/bert_score/utils.py", line 228, in sent_encode
    truncation=True,
  File "/home/cqt/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2227, in encode
    **kwargs,
  File "/home/cqt/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2566, in encode_plus
    **kwargs,
  File "/home/cqt/.local/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 515, in _encode_plus
    **kwargs,
  File "/home/cqt/.local/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 422, in _batch_encode_plus
    pad_to_multiple_of=pad_to_multiple_of,
  File "/home/cqt/.local/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 373, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: int too big to convert`
But for me, it disappeared when I delete the `use_fast_tokenizer=True` option... seems like it is an error in `tokenization_utils_fast.py`

**Comment by atineoSE** [comment]
I am facing the same error when running as follows:
```
bert-score -r example/refs.txt -c example/hyps.txt --lang en -l 5 -m xlnet/xlnet-base-cased --use_fast_tokenizer
```

This is as per the recommendation in the README:
> Please consider using XLNet which can support much longer inputs.

The layer number is as defined [here](https://docs.google.com/spreadsheets/d/1RKOVpselB98Nnh_EOC4A2BYn8_201tmPODpNWu4w7xI/edit#gid=0).

This is the error I get:
```
Some weights of the model checkpoint at xlnet/xlnet-base-cased were not used when initializing XLNetModel: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLNetModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home/ubuntu/apps/SummarizationEval/.venv/bin/bert-score", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score_cli/score.py", line 106, in main
    all_preds, hash_code = bert_score.score(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/score.py", line 123, in score
    all_preds = bert_cos_score_idf(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/utils.py", line 616, in bert_cos_score_idf
    embs, masks, padded_idf = get_bert_embedding(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/utils.py", line 445, in get_bert_embedding
    padded_sens, padded_idf, lens, mask = collate_idf(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/utils.py", line 409, in collate_idf
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/utils.py", line 409, in <listcomp>
    arr = [sent_encode(tokenizer, a) for a in arr]
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/bert_score/utils.py", line 224, in sent_encode
    return tokenizer.encode(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2278, in encode
    encoded_inputs = self.encode_plus(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2610, in encode_plus
    return self._encode_plus(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 499, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 418, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/home/ubuntu/apps/SummarizationEval/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 374, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: int too big to convert
```

I get the same error with and without `--use_fast_tokenizer`.

This is with transformers 4.39.3. I also tried downgrading to transformer 4.21.2, as suggested by @Persvadisto, but I get the same error.

How can I run the XLNet models, please?

**Comment by atineoSE** [comment]
Alright, looks like I could fix it with
```
pip install sentence-piece
```

After that, it works for both transformers 4.39.3 and 4.21.2, but **only** when using `--use_fast_tokenizer`
