### ISSUE TITLE
tokens that exceeds max_len raise error

### ISSUE THREAD

**Issue by inmoonlight** [Tiiiger/bert_score#18]
Hi, authors.
I'm Jennifer and thanks for the implementation.

---
I found that tokens exceeding model's `max_len` raise an error as following:
```
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim =
 -2, IndexIsMajor = true]: block: [22,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim =
 -2, IndexIsMajor = true]: block: [22,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim =
 -2, IndexIsMajor = true]: block: [22,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim =
 -2, IndexIsMajor = true]: block: [22,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim =
 -2, IndexIsMajor = true]: block: [22,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "$PYENV_PATH/bin/mteval", line 11, in <module>
    load_entry_point('mteval===0.5.4-dev-bertscore', 'console_scripts', 'mteval')()
  File "$PYENV_PATH/lib/python3.6/site-packages/mteval/cli.py", line 90, in main
    args.func(args)
  File "$PYENV_PATH/lib/python3.6/site-packages/mteval/_rtt.py", line 39, in mteval_rtt
    mteval_auto(args)
  File "$PYENV_PATH/lib/python3.6/site-packages/mteval/utils.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "$PYENV_PATH/lib/python3.6/site-packages/mteval/_auto.py", line 379, in mteval_auto
    reference_based_evaluation(args)
  File "$PYENV_PATH/lib/python3.6/site-packages/mteval/_auto.py", line 318, in reference_based_evaluation
    P_idf, R_idf, F1_idf = bert_score.score(output_lines, reference_lines, lang=target, idf=True)
  File "$PYENV_PATH/lib/python3.6/site-packages/bert_score/score.py", line 95, in score
    batch_size=batch_size, all_layers=all_layers)
  File "$PYENV_PATH/lib/python3.6/site-packages/bert_score/utils.py", line 276, in bert_cos_score_idf
    embs = embs.cpu()
```

This issue was easily solved by adding one parameter in [`utils.py`](https://github.com/Tiiiger/bert_score/blob/31a26e5336e64fb6046f6a9b67344f571b5d5747/bert_score/utils.py#L111)

If you don't mind, may I do a PR?

**Comment by felixgwu** [comment]
Hi Jennifer,

To our best knowledge, increasing the max_len can't be solved the problem without finetuning the BERT model. The reason is that BERT was trained with at most 512 tokens during the pre-training stage. We got the question before #17. We will update the README to remind the users. Please correct me if I'm wrong.

Best,
Felix

**Comment by inmoonlight** [comment]
Hi @felixgwu,

Thanks for the comments.

By the way, the point was not about increasing `max_len` but cutting off at the `max_len`. 

IMHO, the following code 
https://github.com/Tiiiger/bert_score/blob/ef84afeb88b3eccec1d8728dec33984c56b48a34/bert_score/utils.py#L126
should be modified to
```python
    arr = [tokenizer.encode(a, add_special_tokens=True, max_length=tokenizer.max_len) for a in arr]
```

**Comment by Tiiiger** [comment]
I see. Feel free to create a pull request.

**Comment by fwu-asapp** [comment]
Hi @inmoonlight,
Thanks! Would you like to make a PR? Or I can edit it as well.

**Comment by felixgwu** [comment]
Hi @inmoonlight, 
Would you like to make a PR? Or I can edit.
