### ISSUE TITLE
'T5Stack' object has no attribute 'layer

### ISSUE THREAD

**Issue by danyaljj** [Tiiiger/bert_score#94]
Getting this error when using T5: 
```
Traceback (most recent call last):
  File "/tmp/pycharm_project_808/src/modeling/scratch.py", line 109, in <module>
    scorer = BERTScorer(lang='en', model_type='t5-small')
  File "/home/danielk/end-to-end-modularqa-experiments/env37/lib/python3.7/site-packages/bert_score/scorer.py", line 101, in __init__
    self._model = get_model(self.model_type, self.num_layers, self.all_layers)
  File "/home/danielk/end-to-end-modularqa-experiments/env37/lib/python3.7/site-packages/bert_score/utils.py", line 224, in get_model
    0 <= num_layers <= len(model.encoder.layer)
  File "/home/danielk/end-to-end-modularqa-experiments/env37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'T5Stack' object has no attribute 'layer'
```

Here is my code: 
```
from bert_score import BERTScorer
scorer = BERTScorer(lang='en', model_type='t5-small')
```

I am using the latest version of your code (`pip install git+git://github.com/Tiiiger/bert_score.git#egg=bert-score`) and a relatively recent version of transformers (`transformers==4.1.1`).

**Comment by felixgwu** [comment]
Hi @danyaljj, thank you for raising this issue and sorry for the inconvenience. This problem has been solved in our latest commit. Please feel free to let me know if it still doesn't work for you.

**Comment by Tiiiger** [comment]
closing for now because of inactivity.
